### ISSUE TITLE
06/062019 - Alphabet war

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#1]
[https://www.codewars.com/kata/59377c53e66267c8f6000027](https://www.codewars.com/kata/59377c53e66267c8f6000027)<br><br>
Being the first one proposed, the score for this one is of 1 point once completed

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/5938bdf6371d6aed6600017d/groups/5cfd2a435324de00017014a3

**Comment by jordimarsal** [comment]
https://www.codewars.com/users/jmarsal/completed_solutions

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/5938bdf6371d6aed6600017d/groups/5cfe484aa535d500012970ba

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/5938bdf6371d6aed6600017d/groups/5cfa1ffe5324de000159d351

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/5938bdf6371d6aed6600017d/groups/5cfa176a2ad46500016f9669

**Comment by ta-datapt-bcn** [comment]
Gustavo Denes: https://www.codewars.com/users/gudenes@gmail.com/completed

**Comment by ta-datapt-bcn** [comment]
My solutions
[The large one](https://www.codewars.com/kata/reviews/5938bdf6371d6aed6600017d/groups/5be1520e587efadf13001402)
[Short one](https://www.codewars.com/kata/reviews/5938bdf6371d6aed6600017d/groups/5be165cd3ae6a74d1a001de8)
