### ISSUE TITLE
27/07 - 03/08 | Is he going to survive?

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#10]
Easy as a piece of cake :wink: 
[https://www.codewars.com/kata/is-he-gonna-survive](https://www.codewars.com/kata/is-he-gonna-survive)

**Comment by gudenes** [comment]
https://www.codewars.com/kata/reviews/5bbcd151b6dfbbaa3400248c/groups/5bbd816a6caac6d12b000748

Gustavo Denes
gbdenes@gmail.com (mailto:gbdenes@gmail.com)+34 690 799 392 (tel:+34%20690%20799%20392)

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/5bbcd151b6dfbbaa3400248c/groups/5bbcd187484fcd41870005cc

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/5bbcd151b6dfbbaa3400248c/groups/5bc34c6c55dd993f3f000966

Easy, easy...

**Comment by Jorge2alvarez** [comment]
Done, (No se de donde se consiegue el link para compartir la kata

**Comment by paulagual** [comment]
Jorge, está en Solutions > My Solutions > Link

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/5bbcd151b6dfbbaa3400248c/groups/5bbf56b0605c39153e001958

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/5bbcd151b6dfbbaa3400248c/groups/5bbcdc1f16a8f1a7e0002f99

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/5bbcd151b6dfbbaa3400248c/groups/5bbcdb61484fcd5a08000683)
