### ISSUE TITLE
27/07 - 03/08 | Deodorant Evaporator

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#11]
I think you will enjoy this one :smile: 
[https://www.codewars.com/kata/deodorant-evaporator](https://www.codewars.com/kata/deodorant-evaporator)

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/552fe0b5a063dddb43000018/groups/5d3dea975f69ba0001d608e1

**Comment by gudenes** [comment]
https://www.codewars.com/kata/reviews/552fe0b5a063dddb43000018/groups/5d3e0c0b0356730001e2f198

Gustavo Denes
gbdenes@gmail.com (mailto:gbdenes@gmail.com)+34 690 799 392 (tel:+34%20690%20799%20392)

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/552fe0b5a063dddb43000018/groups/5d3e9c6b5f69ba0001391838

**Comment by Jorge2alvarez** [comment]
Done (No se de donde obtener el link para compartir

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/552fe0b5a063dddb43000018/groups/5d415f6c97f81e0001af9761

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/552fe0b5a063dddb43000018/groups/5d41684097f81e0001af98e0

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/552fe0b5a063dddb43000018/groups/5bd1769fa52de0f7e10025be)
