### ISSUE TITLE
27/07 - 10/08 | Thinkful - Logic Drills: red and bumpy

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#12]
A challenging one. But I know you will not have any issue  with this one
[https://www.codewars.com/kata/thinkful-logic-drills-red-and-bumpy](https://www.codewars.com/kata/thinkful-logic-drills-red-and-bumpy)
Enjoy it! :bomb:

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/5864cde2bf2d67b619001ad9/groups/5d3deedf0356730001e2e106

**Comment by gudenes** [comment]
https://www.codewars.com/kata/reviews/5864cde2bf2d67b619001ad9/groups/5d3e18550356730001e2f2ba

Gustavo Denes
gbdenes@gmail.com (mailto:gbdenes@gmail.com)+34 690 799 392 (tel:+34%20690%20799%20392)

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/5864cde2bf2d67b619001ad9/groups/5d3ea0adc8c979000126f0cc

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/5864cde2bf2d67b619001ad9/groups/5d4161a70356730001bc6c7a

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/5864cde2bf2d67b619001ad9/groups/5d43f6758c4fc1000160a544

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/5864cde2bf2d67b619001ad9/groups/5bcceef40b96aec6f5001463)
