### ISSUE TITLE
Kata Week#15

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#13]
https://www.codewars.com/kata/linear-regression-of-y-on-x/train/python

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/55153961dbc294249c000529/groups/5d8200de01af0600014eacd2

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/55153961dbc294249c000529/groups/5d82278401af0600019a9fae

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/55153961dbc294249c000529/groups/5d89e6885052240001e8d59b
