### ISSUE TITLE
# Kata Week 17

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#15]
6 KYU

https://www.codewars.com/kata/5839edaa6754d6fec10000a2

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/583abab500bb9b40e0000003/groups/5d947e4bb0ad6900010a56f3

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/583abab500bb9b40e0000003/groups/5d972220e1cd9d0001dcce9a
