### ISSUE TITLE
Kata - Factorial

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#19]
https://www.codewars.com/kata/factorial/train/python

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/5d99e5a6ae33860001f17d0a/groups/5dbb39484f2a450001fbf0c9

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/5d99e5a6ae33860001f17d0a/groups/5dbb420b3628170001f43d84
