### ISSUE TITLE
15/06/2019 Find the anonymous function

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#2]

**Comment by ta-datapt-bcn** [comment]
La kata de la semana: <br>
[https://www.codewars.com/kata/find-the-anonymous-function/python](https://www.codewars.com/kata/find-the-anonymous-function/python)

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5d04d6515324de000159f5ef

**Comment by gudenes** [comment]
https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5d053fe6a535d50001807250

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5d075abc0310c20001438f87

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5d087f1c2ad4650001abce9d

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5d090cd6a535d50001b7ffb0

**Comment by ta-datapt-bcn** [comment]
> https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5d075abc0310c20001438f87

Marc, me has utilizado un módulo! XD
Aun así tienes tu punto

**Comment by ta-datapt-bcn** [comment]
My solutions
[Large one](https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5be944813db458189f0001c5)
[Short one](https://www.codewars.com/kata/reviews/55d957d26869dffcc600003d/groups/5be94d3b56b146a8cd00005e)
