### ISSUE TITLE
22/06 to 29/06 Composing squared strings

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#3]
New Kata!<br>
[https://www.codewars.com/kata/56f253dd75e340ff670002ac](https://www.codewars.com/kata/56f253dd75e340ff670002ac)

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/56f254a479a48cce0500002b/groups/5d0e469496bcb900011732d8

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/56f254a479a48cce0500002b/groups/5d0f7d9c0171150001e603db

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/56f254a479a48cce0500002b/groups/5bebe58875977740e10001e4)
