### ISSUE TITLE
29/06 - 06/07 Radio DJ helper function

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#4]
[https://www.codewars.com/kata/561bbcb0fbbfb0f5010000ee](https://www.codewars.com/kata/561bbcb0fbbfb0f5010000ee)

**Comment by gudenes** [comment]
https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5d17bdbf5701e50001472b7f

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5d19dfdffdfc75000194f453

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5d1a11159c6a5800015e9df3

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5d1a150c9c6a5800015ea35a

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5d1b2b5cc940740001e7fd30

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/561cc88a0ccf620085000029/groups/5bf67cb1f8c5274ff90019fd)
