### ISSUE TITLE
02/07 - 16/07 Calculating with functions

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#5]
[https://www.codewars.com/kata/calculating-with-functions](https://www.codewars.com/kata/calculating-with-functions)
This kata has an extraordinary time limit, 2 weeks
It is really hard, many lines of code. But I think is affordable for you
Good Luck! :muscle:

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/5b0ce29de86c548f16000e76/groups/5d1ce5569c6a5800014b72a4

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/5b0ce29de86c548f16000e76/groups/5d1cef73ed0ee500016eb2b1

**Comment by gudenes** [comment]
https://www.codewars.com/users/gudenes@gmail.com/completed_solutions

**Comment by gudenes** [comment]
the solution with more lines win, right?

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/5b0ce29de86c548f16000e76/groups/5bd640cabf185f8bb3002ac3)
<br>
Thank you for participation in this kata challenge, see you in the next one! :wink:
