### ISSUE TITLE
06/07 - 13/07 Decompose single strand dna into 3 reading frames

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#6]
Your weekly Kata!
[https://www.codewars.com/kata/decompose-single-strand-dna-into-3-reading-frames](https://www.codewars.com/kata/decompose-single-strand-dna-into-3-reading-frames)

Enjoy it :stuck_out_tongue_winking_eye:

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/59fb63911917fc9519000034/groups/5d20d949c9407400015c692b

**Comment by gudenes** [comment]
[https://www.codewars.com/kata/reviews/59fb63911917fc9519000034/groups/5d211896ed0ee5000134b315](teste)

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/59fb63911917fc9519000034/groups/5d22fc1eed0ee50001877ed9

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/59fb63911917fc9519000034/groups/5bf51f871a16b063ff0015a7)

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/59fb63911917fc9519000034/groups/5d2efcbea603ab0001b9f866
