### ISSUE TITLE
13/07 - 20/07 ASCII Shift Encryption/Decryption

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#7]
I know you like doing these katas [https://www.codewars.com/kata/ascii-shift-encryption-slash-decryption/python](https://www.codewars.com/kata/ascii-shift-encryption-slash-decryption/python)
Hope you enjoy it! :wink:

**Comment by gudenes** [comment]
https://www.codewars.com/kata/reviews/56ea31b7d742f10914000019/groups/5d2a5a2f7dad940001c3fad3

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/56ea31b7d742f10914000019/groups/5d2b7be5cf09c80001f48864

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/56ea31b7d742f10914000019/groups/5d2c8dce7dad940001e76055

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/56ea31b7d742f10914000019/groups/5d2ef4714e196a0001c4951b

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/56ea31b7d742f10914000019/groups/5d2f2d693afc6600012cbe72

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/56ea31b7d742f10914000019/groups/5a1b9715ce6629d41e0019a3)
