### ISSUE TITLE
13/07 - 27/07 Format words into a sentence

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#8]
And another one, this one is ranked as hard, but I know you can do it [https://www.codewars.com/kata/format-words-into-a-sentence/python](https://www.codewars.com/kata/format-words-into-a-sentence/python)
Have fun fun fun! :stuck_out_tongue_winking_eye:

**Comment by gudenes** [comment]
https://www.codewars.com/kata/reviews/5ac909fe7245a16d6d0005a6/groups/5d2a6902cf09c80001a9dcf1

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/56ea31b7d742f10914000019/groups/5d2b7be5cf09c80001f48864

**Comment by EiroaMD** [comment]
https://www.codewars.com/kata/reviews/5ac909fe7245a16d6d0005a6/groups/5d2b93a9cf09c80001f492c3

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/5ac909fe7245a16d6d0005a6/groups/5d2c8344cf09c8000198570f

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/5ac909fe7245a16d6d0005a6/groups/5d2ef86ca603ab0001b9f82b

**Comment by marcmeji** [comment]
https://www.codewars.com/kata/reviews/5ac909fe7245a16d6d0005a6/groups/5d301ea83afc660001ca432e

**Comment by ta-datapt-bcn** [comment]
[My solution](https://www.codewars.com/kata/reviews/5ac909fe7245a16d6d0005a6/groups/5bf1e55cf8c527ef4400135e)
