### ISSUE TITLE
21/07 - 27/07 Geometry Basics: Cross Product in 3D

### ISSUE THREAD

**Issue by ta-datapt-bcn** [ta-datapt-bcn/katas_challenge#9]
An easy one :bomb:  for this busy week
[https://www.codewars.com/kata/geometry-basics-cross-product-in-3d/python](https://www.codewars.com/kata/geometry-basics-cross-product-in-3d/python)
Have fun fun fun! :dancer: :dancer:

**Comment by MartinPeTo** [comment]
https://www.codewars.com/kata/reviews/58e4468746e371d5220012be/groups/5d349e6126fd25000163c4da

**Comment by paulagual** [comment]
https://www.codewars.com/kata/reviews/58e4468746e371d5220012be/groups/5d34ce83ea8e3300018d9e07

**Comment by marcmeji** [comment]
Me han puesto en el "saco" de estas soluciones y no como obtener el link a la mia en particular:

https://www.codewars.com/kata/reviews/58e4468746e371d5220012be/groups/58e4468846e371323b0012c4

**Comment by ta-datapt-bcn** [comment]
Do not worry Marc, me too :laughing: 
[My solution](https://www.codewars.com/kata/reviews/58e4468746e371d5220012be/groups/58e4468846e371323b0012c4)
